[workspace]
authors = ["Suganya Sivagurunathan <suganya.nathan@gmail.com>"]
channels = ["conda-forge"]
name = "I2KWorkshop_2026"
platforms = ["win-64", "linux-64", "osx-arm64"]
version = "0.1.0"

[activation.env]
MKL_THREADING_LAYER = "SEQUENTIAL"

[dependencies]
pip = "*"
ipykernel = "*"
jupyter = "*"

[feature.spatial.dependencies]
python = "3.12.*"
numpy = ">=1.26,<3"
matplotlib = ">=3.8,<4"
pandas = ">=2,<3"
tifffile = "*"
scikit-image = ">=0.22,<0.27"
spatialdata = ">=0.8.0,<0.9"

[feature.spatial.pypi-dependencies]
spatialdata-plot = ">=0.4.2,<0.5"
spatialdata-io = "*"

[feature.registration.dependencies]
python = "3.11.*"
numpy = ">=1.26,<3"
matplotlib = ">=3.8,<4"
pandas = ">=2,<3"
tifffile = "*"
scikit-image = ">=0.22,<0.27"

[feature.registration.pypi-dependencies]
itk = ">=5.4,<6"
itk-elastix = "*"

[environments]
spatial = ["spatial"]
registration = ["registration"]